// scoreGrid — pure function of a FINISHED grid, per flip-toonz-structure-plan.md
// §4.1: "Because no placement ability grants fame, scoring is not a running
// total that effects mutate." Same grid in -> same breakdown out, regardless
// of the order cards were placed in.
//
// Season-agnostic (§10): takes cards as data, never branches on Card.season.
//
// NOT implemented here, by design, per the task scope for Step 0:
//   - postFameHook (Skunk/Firefly category, §3.4) needs a cross-player fame
//     comparison that doesn't exist with a single grid. scoreGrid scores the
//     Skunk's own fame.base (0) and does not attempt the hook — see §10:
//     "the Skunk needs a cross-player fame comparison that doesn't exist here."
//   - roundFame's Critic's Choice +3 (§3.2.1) — that's a per-player modifier
//     layered on top of scoreGrid, not part of it, and doesn't exist until
//     the phase machine does.
//
// FAME vs. EFFECT incompleteness (see cards/types.ts's Card comment): only
// `card.fameUnencodable` (or `fame.base === '=' ` as a belt-and-braces
// backstop — see the branch condition below) makes scoreGrid blank a card's
// score. A card whose onPlace/onHire/onDismiss effect is still `unencodable`
// but whose `fame` is a normal number scores completely normally here —
// that's the whole point of splitting the two flags.
//
// COW ('=' fame): per a direct ruling from the user (overriding this file's
// earlier "report all candidates, let the player choose" draft), the Cow's
// fame is DETERMINISTIC, not a player choice: it equals the MAXIMUM fame
// among its adjacent face-up cards (stacks expanded — every face-up member
// of an adjacent stack is its own candidate, per the FAQ: "you may copy any
// one card's fame in the stack" — a rational player always takes the max,
// so "may copy any one" collapses to "copies the best one"). Since a Cow
// can be adjacent to another Cow, resolution runs as a small fixpoint over
// the whole grid (see resolveCowFame below) rather than a single pass.
//
// DOG (dogInMarketOrOtherPlayerGrid): unlike the Cow, this reads state
// scoreGrid genuinely does not have (the shared market, every OTHER
// player's grid — deliberately excludes the grid being scored itself).
// Rather than block it behind `fameUnencodable` like Platypus (the last
// card still stuck there — Big Button is a missing physical component, not
// missing multiplayer state), scoreGrid takes an explicit, narrowly-scoped
// `externalState.dogElsewhere` parameter (a Check-Fame-time SNAPSHOT — name
// it and treat it that way; a future Market phase must not read this
// live, per the Dog's own FAQ note: "fame generated by the dog is not
// affected by changes to the market in the Market phase"). When provided
// (true or false), Dog scores normally off that boolean. When omitted,
// scoreGrid computes BOTH branches for every Dog in the grid and reports
// them via FameLine.dualBranch / FameBreakdown.totalBranches instead of
// picking one. All Dogs in one grid share the same external fact, so this
// is two branches, not 2^n.
//
// CAMEL (noOneHasMoreCamelsThanYou): same missing-state category as Dog —
// "the players' grids and/or the market" — but solo has no other players,
// so this always reduces to a single comparable count (your grid's Camels
// vs. the market's), never an ambiguous "elsewhere" boolean. Resolved via
// `externalState.camelMarketCount` unconditionally (no dual-branch case —
// see evaluateBonus's 'noOneHasMoreCamelsThanYou' handler).
//
// FOX (henOrRoosterInMarketOrAnyGrid): unlike Dog's "any OTHER player's
// grid" (Dog excludes itself, or its own condition would be tautological —
// it references Dog), Fox's card text says "any player's grid" with no
// "other" — Fox references Hen/Rooster, different cards, so its own grid
// counts. That half is ordinary grid state scoreGrid already has. Only the
// shared market is missing, and only when the own-grid check doesn't
// already decide it: a Hen or Rooster face-up in this grid satisfies the
// condition outright, no external input needed at all. Otherwise resolved
// via `externalState.henOrRoosterInMarket` unconditionally, same
// throw-when-missing shape as Camel (no dual-branch case) — see
// evaluateBonus's 'henOrRoosterInMarketOrAnyGrid' handler.

import type { Card, CardId, FameBonus } from './cards/types'
import { adjacentFaceUpCardIds, adjacentPositions, columnPositions, getSlot, occupiedSlots } from './grid'
import type { Grid, GridPos } from './types'

export type FameBonusLine = {
  reason: string
  amount: number
}

export type FameLine = {
  pos: GridPos
  cardId: CardId
  name: string
  base: number | null // null when needsRuling — no single fame value is trustworthy
  bonuses: FameBonusLine[]
  total: number
  needsRuling?: boolean
  needsRulingReason?: string
  // Set only for a resolved Cow-shaped ('=') card: which adjacent card its
  // copied fame came from, for a transparent breakdown ("copied from
  // Elephant at base[0][2]") rather than a bare number.
  copiedFrom?: { cardId: CardId; name: string; pos: GridPos }
  // Set only for a card whose fame depends on external state that wasn't
  // provided (Dog's `dogInMarketOrOtherPlayerGrid` condition when
  // scoreGrid's `externalState.dogElsewhere` is omitted — see scoreGrid's
  // header comment). Unlike `needsRuling` (which means the value genuinely
  // CANNOT be computed), both branches here ARE fully computable — there
  // just isn't a single answer without the missing external fact, so both
  // are shown instead of guessing or blanking. `base`/`bonuses`/`total`
  // above are left at a conservative placeholder (the false/0 branch) when
  // this is set; read `dualBranch` for the real numbers.
  dualBranch?: { label: string; base: number; bonuses: FameBonusLine[]; total: number }[]
}

export type FameBreakdown = {
  total: number
  lines: FameLine[]
  // Set only when at least one line has `dualBranch` — the grid-level
  // mirror of that per-line ambiguity (§ task "the grid TOTAL problem"):
  // there is no single grid total when a Dog's condition is unresolved, so
  // this carries the two possible totals instead. All dual-branch lines in
  // one grid share the SAME external fact (one Check-Fame-time snapshot,
  // not per-card), so this is exactly two totals, never 2^n.
  totalBranches?: { label: string; total: number }[]
}

// Branch labels for Dog's dual-branch presentation — shared between the
// per-line dualBranch entries and the grid-level totalBranches so the UI
// (formatBreakdown) can pair them up by string equality if needed.
const DOG_ELSEWHERE_FALSE_LABEL = 'if no Dog elsewhere'
const DOG_ELSEWHERE_TRUE_LABEL = 'if a Dog is present elsewhere'

function posLabel(pos: GridPos): string {
  // BUG FIX (this pass): must include `row` for extra positions too, now
  // that extraRows can stack more than one — `extra[${col}]` alone
  // collapsed every row in a column to the same label, which fed slotKey()
  // below into `resolvedTotals`/`cowSource` (the Cow fame-relaxation maps
  // keyed off this string) and would have silently made a stacked column's
  // second row's resolved fame overwrite the first's, corrupting an
  // adjacent Cow's copied value. Caught by review, not a failing test —
  // see season2-effects.test.ts for the coverage this bug's absence pointed
  // at (extra-row-to-extra-row adjacency had no test at all before).
  return pos.section === 'base' ? `base[${pos.row}][${pos.col}]` : `extra[${pos.row}][${pos.col}]`
}

function slotKey(pos: GridPos, index: number): string {
  return `${posLabel(pos)}#${index}`
}

// All face-up (cardId, card) entries anywhere in the grid — base + extraRows,
// every stack member — for the "whole grid" queries (Rooster, Hen, Bear,
// Deer, Bull, Sloth, Goldfish/Shark's fishTypeCard). Per the Flip keyword
// ("a face-down card has no name, rank, special effects, or abilities and
// does not generate fame"), face-down cards are excluded from every query
// keyed on a card's NAME, RANK, or TYPE — those attributes simply don't
// exist for a face-down card. Queries keyed on raw CARD COUNT instead
// (Sloth's `gridHasAtLeastEightCards`, Grasshopper/Spider's stack-position
// queries below) go the other way: "a face-down card ... is still a card
// and takes a slot in a player's grid," so those count face-down cards too.
// This split is the one principle behind every handler in this file, not a
// per-card judgment call — cited here once instead of re-derived per query.
function allFaceUpGridEntries(grid: Grid): { pos: GridPos; cardId: CardId }[] {
  const entries: { pos: GridPos; cardId: CardId }[] = []
  for (const { pos, slot } of occupiedSlots(grid)) {
    for (let i = 0; i < slot.cards.length; i++) {
      if (slot.faceUp[i]) entries.push({ pos, cardId: slot.cards[i] })
    }
  }
  return entries
}

// Sum of slot.cards.length over every OTHER occupied slot in `pos`'s
// column, strictly above or below `pos` (per `columnPositions`' top-to-bottom
// order) — used by Grasshopper/Spider (§4.4). Counts every card in a
// counted slot regardless of face-up/down state (ruled directly by user
// 2026-08-20: this is a column count, not a same-slot stack count — a
// slot's own cards, including `pos`'s own stack, never contribute).
function countCardsInColumn(grid: Grid, pos: GridPos, direction: 'above' | 'below'): number {
  const col = pos.col
  const column = columnPositions(grid, col)
  const ownIndex = column.findIndex((p) => p.section === pos.section && p.row === pos.row)
  if (ownIndex === -1) throw new Error(`score.ts: countCardsInColumn — ${JSON.stringify(pos)} not found in its own column`)
  const range = direction === 'above' ? column.slice(0, ownIndex) : column.slice(ownIndex + 1)
  return range.reduce((sum, p) => {
    const slot = getSlot(grid, p)
    return sum + (slot ? slot.cards.length : 0)
  }, 0)
}

// Evaluate a single FameBonus for one card at one grid position (`index`
// is this card's own position within its slot's stack — bottom-to-top,
// per `Slot`'s doc comment — needed only by the stack-position queries
// below). Grows with the query/condition vocabulary in cards/types.ts
// (§4.4) — only the queries actually needed by an encoded card are
// implemented; anything else throws rather than silently scoring zero.
function evaluateBonus(
  bonus: FameBonus,
  grid: Grid,
  pos: GridPos,
  index: number,
  cardsById: Record<CardId, Card>,
  remainingDeckSize: number | undefined,
  dogElsewhere: boolean | undefined,
  dismissed: CardId[] | undefined,
  camelMarketCount: number | undefined,
  henOrRoosterInMarket: boolean | undefined,
): FameBonusLine {
  if (bonus.kind === 'perQuery' && bonus.query === 'dismissedStartingCard') {
    // Cat: "+1 PER dismissed STARTING card (rank 0)" — counts every entry in
    // the dismissed pile whose card is rank 0, per setup.ts's own
    // starting-deck builders (rank 0 = starting-deck-only). Same house style
    // as Capybara/Hippopotamus's remainingDeckSize guard below: "not given"
    // is NOT "empty" — throws rather than silently scoring 0.
    if (dismissed === undefined) {
      throw new Error(
        "score.ts: bonus 'dismissedStartingCard' (Cat) needs externalState.dismissed — pass it as scoreGrid's fourth argument",
      )
    }
    const count = dismissed.filter((id) => cardsById[id].rank === 0).length
    return { reason: `${count} dismissed starting card(s)`, amount: count * bonus.amount }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'dismissedCard') {
    // Tiger: "+1 PER dismissed card" — flat count, any card, any rank.
    if (dismissed === undefined) {
      throw new Error(
        "score.ts: bonus 'dismissedCard' (Tiger) needs externalState.dismissed — pass it as scoreGrid's fourth argument",
      )
    }
    return { reason: `${dismissed.length} dismissed card(s)`, amount: dismissed.length * bonus.amount }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'dismissedIdenticalPair') {
    // Opossum: "+2 PER pair of identical dismissed cards" — pairs, not
    // singles: Math.floor(count/2) per distinct id, summed across ids.
    if (dismissed === undefined) {
      throw new Error(
        "score.ts: bonus 'dismissedIdenticalPair' (Opossum) needs externalState.dismissed — pass it as scoreGrid's fourth argument",
      )
    }
    const countsById = new Map<CardId, number>()
    for (const id of dismissed) countsById.set(id, (countsById.get(id) ?? 0) + 1)
    let pairs = 0
    for (const count of countsById.values()) pairs += Math.floor(count / 2)
    return { reason: `${pairs} dismissed identical pair(s)`, amount: pairs * bonus.amount }
  }


  if (bonus.kind === 'ifCondition' && bonus.condition === 'dogInMarketOrOtherPlayerGrid') {
    // Only reached when dogElsewhere is resolved to a concrete boolean —
    // either the caller passed scoreGrid's externalState.dogElsewhere
    // explicitly, or scoreGrid is evaluating one of the two dual-branch
    // candidates itself (see scoreGrid's dual-branch handling below, which
    // calls computeCardFame twice, once per boolean, rather than ever
    // calling this with dogElsewhere undefined).
    if (dogElsewhere === undefined) {
      throw new Error(
        "score.ts: evaluateBonus reached Dog's condition with dogElsewhere undefined — scoreGrid should resolve both branches via computeCardFame before calling evaluateBonus, not leave this ambiguous",
      )
    }
    return {
      reason: dogElsewhere ? 'a Dog is in the market or another player\'s grid' : 'no Dog in the market or another player\'s grid',
      amount: dogElsewhere ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'noOneHasMoreCamelsThanYou') {
    // Camel: solo has no other players (same reduction Dog's own solo
    // resolution uses — see phases.ts's camelMarketCountFromMarket), so
    // this condition reduces to "your own grid's Camel count is at least
    // the market's Camel count" — ties qualify, per the FAQ quoted on the
    // card. Like Capybara/Hippopotamus's remainingDeckSize, this throws
    // rather than silently scoring 0 when the caller hasn't provided it.
    if (camelMarketCount === undefined) {
      throw new Error(
        "score.ts: bonus 'noOneHasMoreCamelsThanYou' (Camel) needs externalState.camelMarketCount — pass it as scoreGrid's fourth argument",
      )
    }
    const ownCamelCount = allFaceUpGridEntries(grid).filter((e) => e.cardId === 'camel').length
    const satisfied = ownCamelCount >= camelMarketCount
    return {
      reason: satisfied
        ? `no one has more camels than you (you: ${ownCamelCount}, market: ${camelMarketCount})`
        : `the market has more camels than you (you: ${ownCamelCount}, market: ${camelMarketCount})`,
      amount: satisfied ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'henOrRoosterInMarketOrAnyGrid') {
    // Fox: "+3 if there is at least one Hen or Rooster in the market or any
    // player's grid" — unlike Dog's "any OTHER player's grid", Fox's own
    // grid counts (see this file's header comment). Check own grid first;
    // a Hen or Rooster face-up here satisfies the condition outright and
    // needs no external input at all.
    const ownGridHasHenOrRooster = allFaceUpGridEntries(grid).some((e) => e.cardId === 'hen' || e.cardId === 'rooster')
    if (ownGridHasHenOrRooster) {
      return { reason: 'a Hen or Rooster is in your own grid', amount: bonus.amount }
    }
    if (henOrRoosterInMarket === undefined) {
      throw new Error(
        "score.ts: bonus 'henOrRoosterInMarketOrAnyGrid' (Fox) needs externalState.henOrRoosterInMarket — pass it as scoreGrid's fourth argument",
      )
    }
    return {
      reason: henOrRoosterInMarket ? 'a Hen or Rooster is in the market' : 'no Hen or Rooster in the market or your grid',
      amount: henOrRoosterInMarket ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'uniqueAdjacentName') {
    // Dragonfly: count DISTINCT NAMES among orthogonally-adjacent face-up
    // cards (including every face-up member of an adjacent stack). Two
    // Caterpillars adjacent count once, not twice — confirmed by direct user
    // ruling, §7 question 4c.
    const adjacentIds = adjacentFaceUpCardIds(grid, pos)
    const distinctNames = new Set(adjacentIds.map((id) => cardsById[id].name))
    const n = distinctNames.size
    return {
      reason: `unique adjacent: ${[...distinctNames].join(', ') || 'none'}`,
      amount: n * bonus.amount,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'inUpperRow') {
    // Goat: "+3 if placed in the upper row" (base 1 otherwise). Season 1's
    // FAQ: "If a monkey creates a new row above the upper row, the goat's
    // ability still activates" — i.e. this must stay keyed to the grid's
    // BASE upper row (base row 0) specifically, never `extraRow`, no matter
    // how many extra rows a Monkey/Gorilla has stacked above it. That falls
    // out for free here: `extraRow` is a completely separate GridPos
    // section from `base`, so a card sitting there can never match
    // `pos.section === 'base' && pos.row === 0` — no extra-row-awareness
    // needed. See score.test.ts's Goat regression test.
    const inUpperRow = pos.section === 'base' && pos.row === 0
    return {
      reason: inUpperRow ? 'in upper row' : 'not in upper row',
      amount: inUpperRow ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'inLowerRow') {
    // Donkey: "+5 if placed in the lower row" (base 1 otherwise). Confirmed
    // by the FAQ ("if a donkey is placed in the upper row of a grid, it is
    // not dismissed" — the fame bonus and the (unencoded, effect-only)
    // self-dismiss share this same condition). Row 1 is the lower row in
    // this grid model (row 0 sits directly under extraRow, i.e. is "upper").
    const inLowerRow = pos.section === 'base' && pos.row === 1
    return {
      reason: inLowerRow ? 'in lower row' : 'not in lower row',
      amount: inLowerRow ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'inMiddleColumn') {
    // Sheep: "+4 if in the middle column" (base 1 otherwise). Column 1 is
    // the middle of the 3-wide grid, in either base row or the extraRow —
    // same `pos.col === 1` convention flip.ts's Crab effect already uses.
    const inMiddleColumn = pos.col === 1
    return {
      reason: inMiddleColumn ? 'in middle column' : 'not in middle column',
      amount: inMiddleColumn ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'perCardRank13OrLowerIncludingSelf') {
    // Rooster: "+1 PER card rank 13 or lower (including this card)" — a
    // COUNT, not a flat yes/no, despite being encoded as `ifCondition` in
    // season1.ts (bug: the original encoding treated this as a boolean
    // all-or-nothing bonus, which would have scored +1 instead of +N).
    // types.ts's own comment sanctions this: "condition is human text
    // until a query vocabulary is built for it" — so `ifCondition` isn't
    // strictly boolean, and the minimal fix is computing the count here
    // rather than widening the FameBonus union to a new perQuery member.
    // Face-down cards have no rank (Flip keyword) and are excluded.
    const matches = allFaceUpGridEntries(grid).filter((e) => cardsById[e.cardId].rank <= 13)
    return {
      reason: `${matches.length} card(s) rank 13 or lower`,
      amount: matches.length * bonus.amount,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'perCardRank6OrHigherIncludingSelf') {
    // Hen: "+1 PER card rank 6 or higher (including this card)" — same
    // count-not-boolean bug/fix as Rooster above. Hen is itself rank 6, so
    // it always counts itself at minimum.
    const matches = allFaceUpGridEntries(grid).filter((e) => cardsById[e.cardId].rank >= 6)
    return {
      reason: `${matches.length} card(s) rank 6 or higher`,
      amount: matches.length * bonus.amount,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'allFaceUpAdjacentRank16OrLower') {
    // Lion: "+4 if all face-up adjacent cards are rank 16 or lower" (base 3
    // otherwise). "All X are Y" is vacuously true over an empty set — a
    // Lion with no face-up adjacent cards at all gets the bonus, which is
    // the plain reading of the text, not a guess to hide: the reason
    // string below says so explicitly rather than silently handing out +4.
    const adjacentIds = adjacentFaceUpCardIds(grid, pos)
    const allAtMost16 = adjacentIds.every((id) => cardsById[id].rank <= 16)
    return {
      reason:
        adjacentIds.length === 0
          ? 'no adjacent face-up cards — vacuously satisfied'
          : allAtMost16
            ? 'all face-up adjacent cards rank 16 or lower'
            : 'at least one face-up adjacent card above rank 16',
      amount: allAtMost16 ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'atLeastOneFaceDownCardInGrid') {
    // Bull: "+7 if one or more cards in your grid are face down" (base 3
    // otherwise). This condition is explicitly ABOUT face-down cards, so
    // (unlike the name/rank queries above) it must scan every card
    // including face-down ones — occupiedSlots()'s slots include them,
    // this is the one query in this file that reads `slot.faceUp` looking
    // for `false` rather than filtering it out.
    let hasFaceDown = false
    for (const { slot } of occupiedSlots(grid)) {
      if (slot.faceUp.includes(false)) {
        hasFaceDown = true
        break
      }
    }
    return {
      reason: hasFaceDown ? 'at least one face-down card in grid' : 'no face-down cards in grid',
      amount: hasFaceDown ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'allFaceUpGridCardsUnique') {
    // Deer: "+5 if each face-up card in your grid is unique" (base 3
    // otherwise) — every face-up card (whole grid, stacks expanded) has a
    // distinct NAME. Card text says "face-up" explicitly, so face-down
    // cards are excluded (they have no name to compare, per the Flip
    // keyword) rather than an inferred choice.
    const entries = allFaceUpGridEntries(grid)
    const names = entries.map((e) => cardsById[e.cardId].name)
    const allUnique = names.length === new Set(names).size
    return {
      reason: allUnique ? 'all face-up grid cards unique' : 'at least one duplicate face-up card name',
      amount: allUnique ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'gridHasAtLeastEightCards') {
    // Sloth: "+5 if your grid has at least eight cards" (base 3 otherwise)
    // — a raw CARD COUNT, so (per this function's header comment) it
    // counts every card regardless of face state: "a face-down card ...
    // is still a card and takes a slot in a player's grid."
    let count = 0
    for (const { slot } of occupiedSlots(grid)) count += slot.cards.length
    return {
      reason: `${count} card(s) in grid`,
      amount: count >= 8 ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'adjacentToAtLeastOneFishCard') {
    // Clownfish: "+2 if adjacent to at least one FISH card" (base 3
    // otherwise). Face-up adjacent cards only — a face-down card has no
    // type (Flip keyword).
    const adjacentIds = adjacentFaceUpCardIds(grid, pos)
    const hasFish = adjacentIds.some((id) => cardsById[id].typeTags?.includes('fish'))
    return {
      reason: hasFish ? 'adjacent to at least one fish card' : 'no adjacent fish card',
      amount: hasFish ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'ifCondition' && bonus.condition === 'atLeastThreeCardsRemainingInDeck') {
    // Capybara: "+4 if there are at least three cards remaining in your
    // deck" (base 2 otherwise). scoreGrid is a pure function of a
    // FINISHED grid (§4.1) and has no deck by default — `remainingDeckSize`
    // is an optional extra input threaded in by the caller (flipDeck's
    // FlipResult.remainingDeck.length). Throws rather than
    // silently treating "no deck size given" as zero, since that would
    // score confidently wrong instead of visibly incomplete.
    if (remainingDeckSize === undefined) {
      throw new Error(
        "score.ts: bonus 'atLeastThreeCardsRemainingInDeck' (Capybara) needs remainingDeckSize — pass it as scoreGrid's third argument",
      )
    }
    const atLeastThree = remainingDeckSize >= 3
    return {
      reason: `${remainingDeckSize} card(s) remaining in deck`,
      amount: atLeastThree ? bonus.amount : 0,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'faceUpGridCard') {
    // Bear: "+1 PER face-up card in your grid" (including itself — FAQ:
    // "the bear counts all face-up stacked cards as well as itself").
    const entries = allFaceUpGridEntries(grid)
    return {
      reason: `${entries.length} face-up card(s) in grid`,
      amount: entries.length * bonus.amount,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'fishTypeCard') {
    // Goldfish: "+1 PER FISH card (including this card)". Shark: "+1 PER
    // FISH card" — same query, no "including this card" wording, and
    // correctly self-excluding for free because season2.ts's Shark entry
    // deliberately has no `typeTags: ['fish']` (FAQ: "the Shark itself
    // does not count as a fish type card", noted in season2.ts). Both
    // count grid-wide (no "adjacent" wording on either card), face-up only
    // (a face-down card has no type).
    const entries = allFaceUpGridEntries(grid).filter((e) => cardsById[e.cardId].typeTags?.includes('fish'))
    return {
      reason: `${entries.length} fish card(s) in grid`,
      amount: entries.length * bonus.amount,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'adjacentOddRankCard') {
    // Rhinoceros: "+3 PER adjacent odd rank card". Face-up adjacent cards
    // only (a face-down card has no rank).
    const adjacentIds = adjacentFaceUpCardIds(grid, pos)
    const oddCount = adjacentIds.filter((id) => cardsById[id].rank % 2 === 1).length
    return {
      reason: `${oddCount} adjacent odd-rank card(s)`,
      amount: oddCount * bonus.amount,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'remainingDeckCard') {
    // Hippopotamus: "+2 PER card remaining in your deck" — same
    // remainingDeckSize input as Capybara above (this pass extends
    // scoreGrid's signature to carry it; both cards needed the same
    // missing input, confirming it's a real signature gap, not two
    // separate small additions).
    if (remainingDeckSize === undefined) {
      throw new Error(
        "score.ts: bonus 'remainingDeckCard' (Hippopotamus) needs remainingDeckSize — pass it as scoreGrid's third argument",
      )
    }
    return {
      reason: `${remainingDeckSize} card(s) remaining in deck`,
      amount: remainingDeckSize * bonus.amount,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'cardAboveInColumn') {
    // Grasshopper: "+1 PER card above this card" — a COLUMN count, not a
    // same-slot stack count (ruled directly by user 2026-08-20, overriding
    // this file's earlier same-stack reading). Counts every card in every
    // OTHER slot above this one in the same column (toward extraRows),
    // regardless of face-up/down state — cards within Grasshopper's own
    // slot are excluded, since those belong to the (separate) same-stack
    // question, not the column one.
    const countAbove = countCardsInColumn(grid, pos, 'above')
    return {
      reason: `${countAbove} card(s) above in column`,
      amount: countAbove * bonus.amount,
    }
  }

  if (bonus.kind === 'perQuery' && bonus.query === 'cardBelowInColumn') {
    // Spider: "+1 PER card below this card" — column count, mirror of
    // Grasshopper above (ruled directly by user 2026-08-20).
    const countBelow = countCardsInColumn(grid, pos, 'below')
    return {
      reason: `${countBelow} card(s) below in column`,
      amount: countBelow * bonus.amount,
    }
  }

  throw new Error(
    `score.ts: no handler for bonus ${JSON.stringify(bonus)} — grow the query vocabulary in score.ts before scoring a card that uses it (see cards/types.ts GridQuery/FameBonus)`,
  )
}

type ComputedFame = { base: number; bonusLines: FameBonusLine[]; total: number }

// Computes a card's OWN fame (base + bonuses) at a position. Only called for
// cards that are neither Cow-shaped ('=') nor otherwise fameUnencodable —
// scoreGrid filters those out before calling this, and resolves Cow-shaped
// cards separately via resolveCowFame.
function computeCardFame(
  cardId: CardId,
  pos: GridPos,
  index: number,
  grid: Grid,
  cardsById: Record<CardId, Card>,
  remainingDeckSize: number | undefined,
  dogElsewhere: boolean | undefined,
  dismissed: CardId[] | undefined,
  camelMarketCount: number | undefined,
  henOrRoosterInMarket: boolean | undefined,
): ComputedFame {
  const card = cardsById[cardId]
  if (!card) throw new Error(`score.ts: unknown card id ${cardId}`)
  if (card.fame.base === '=') {
    throw new Error(`score.ts: computeCardFame called on Cow-shaped card ${card.name} — should go through resolveCowFame instead`)
  }
  const base = card.fame.base
  const bonusLines = (card.fame.bonuses ?? []).map((b) =>
    evaluateBonus(b, grid, pos, index, cardsById, remainingDeckSize, dogElsewhere, dismissed, camelMarketCount, henOrRoosterInMarket),
  )
  const total = base + bonusLines.reduce((sum, b) => sum + b.amount, 0)
  return { base, bonusLines, total }
}

// Whether this card's fame rule contains the Dog's external-state
// condition. Deliberately keyed on the CONDITION STRING, not `card.id ===
// 'dog'` — narrower than a season/id special case, and automatically
// covers any future card sharing this exact condition without another
// hardcoded id.
function hasDogElsewhereCondition(card: Card): boolean {
  return (card.fame.bonuses ?? []).some((b) => b.kind === 'ifCondition' && b.condition === 'dogInMarketOrOtherPlayerGrid')
}

// Every face-up card adjacent to `pos` (stacks expanded), as {key, cardId,
// pos} triples, where `key` is the same slotKey used to look values up in
// `resolvedTotals` below.
function adjacentFaceUpEntries(pos: GridPos, grid: Grid): { key: string; cardId: CardId; pos: GridPos }[] {
  const entries: { key: string; cardId: CardId; pos: GridPos }[] = []
  for (const neighborPos of adjacentPositions(grid, pos)) {
    const slot = getSlot(grid, neighborPos)
    if (!slot) continue
    for (let i = 0; i < slot.cards.length; i++) {
      if (!slot.faceUp[i]) continue
      entries.push({ key: slotKey(neighborPos, i), cardId: slot.cards[i], pos: neighborPos })
    }
  }
  return entries
}

// `remainingDeckSize` is optional and only needed by cards whose fame bonus
// reads deck state (Capybara/Hippopotamus — see evaluateBonus). scoreGrid
// stays a pure function of "whatever's passed in," per §4.1 — this is an
// extra INPUT, not a mutation or a lookup into hidden state; pass
// `FlipResult.remainingDeck.length` from flipDeck's return value. Omitting
// it is fine for grids with no such card; a grid that
// needs it and doesn't get it throws (see evaluateBonus), rather than
// silently scoring 0.
export function scoreGrid(
  grid: Grid,
  cardsById: Record<CardId, Card>,
  remainingDeckSize?: number,
  externalState?: { dogElsewhere?: boolean; dismissed?: CardId[]; camelMarketCount?: number; henOrRoosterInMarket?: boolean }, // Check-Fame-time snapshot — see the Dog comment above; never read live once a Market phase exists
): FameBreakdown {
  const lines: FameLine[] = []
  const resolvedTotals = new Map<string, number>() // slotKey -> resolved fame, filled in as cards resolve
  const cowEntries: { key: string; pos: GridPos; line: FameLine }[] = []
  // slotKeys of every dualBranch line (Dog's unresolved condition) pushed in
  // pass 1 below. A Cow adjacent to one of these has no single fame value
  // either — see the cowEntries loop in pass 2, which checks this rather
  // than silently picking a branch (a Cow next to an unresolved Dog would
  // otherwise copy whatever OTHER neighbor happens to be in resolvedTotals
  // and ignore the Dog entirely, understating its true-branch value).
  const dualBranchKeys = new Set<string>()

  // Pass 1: every face-up occupied card gets a line. Regular cards are
  // fully computed and their total recorded in `resolvedTotals` immediately
  // (nothing in the vocabulary besides Cow depends on another card's
  // resolved fame, so this can happen in a single straightforward pass).
  // Cow-shaped ('=') cards get a placeholder line now — pushed in the
  // correct reading-order position — and are resolved in pass 2 below,
  // since a Cow may need another Cow's value first.
  for (const { pos, slot } of occupiedSlots(grid)) {
    for (let i = 0; i < slot.cards.length; i++) {
      if (!slot.faceUp[i]) continue // face-down cards contribute nothing (§3.3a)

      const cardId = slot.cards[i]
      const card = cardsById[cardId]
      if (!card) throw new Error(`score.ts: unknown card id ${cardId}`)
      const key = slotKey(pos, i)

      // Branch on `fame.base === '=' || fameUnencodable`, not either flag
      // alone: makes it structurally impossible for a '=' card missing the
      // flag (a data-entry slip) to fall through and score as if '=' were a
      // number, and equally impossible for a flagged-but-numeric card to be
      // treated as dynamic.
      if (card.fame.base === '=') {
        const line: FameLine = { pos, cardId, name: card.name, base: null, bonuses: [], total: 0 }
        lines.push(line)
        cowEntries.push({ key, pos, line })
        continue
      }
      if (card.fameUnencodable) {
        lines.push({
          pos,
          cardId,
          name: card.name,
          base: null,
          bonuses: [],
          total: 0,
          needsRuling: true,
          needsRulingReason: card.fameUnencodableReason ?? 'fame value cannot be computed as a fixed number',
        })
        continue // not added to resolvedTotals — an unresolvable card can't anchor a Cow's copy either
      }

      // Dog's dual-branch case: externalState.dogElsewhere wasn't given, so
      // there's no single answer — compute BOTH branches (each a full,
      // independent computeCardFame call, not just the one differing
      // bonus, in case a future card sharing this condition also has other
      // bonuses) and report both rather than guessing or blanking.
      if (hasDogElsewhereCondition(card) && externalState?.dogElsewhere === undefined) {
        const falseBranch = computeCardFame(cardId, pos, i, grid, cardsById, remainingDeckSize, false, externalState?.dismissed, externalState?.camelMarketCount, externalState?.henOrRoosterInMarket)
        const trueBranch = computeCardFame(cardId, pos, i, grid, cardsById, remainingDeckSize, true, externalState?.dismissed, externalState?.camelMarketCount, externalState?.henOrRoosterInMarket)
        lines.push({
          pos,
          cardId,
          name: card.name,
          base: falseBranch.base,
          bonuses: falseBranch.bonusLines,
          total: falseBranch.total, // conservative placeholder — see dualBranch for both real numbers
          dualBranch: [
            { label: DOG_ELSEWHERE_FALSE_LABEL, base: falseBranch.base, bonuses: falseBranch.bonusLines, total: falseBranch.total },
            { label: DOG_ELSEWHERE_TRUE_LABEL, base: trueBranch.base, bonuses: trueBranch.bonusLines, total: trueBranch.total },
          ],
        })
        dualBranchKeys.add(key)
        continue // not added to resolvedTotals — ambiguous, can't anchor a Cow's copy either
      }

      const computed = computeCardFame(cardId, pos, i, grid, cardsById, remainingDeckSize, externalState?.dogElsewhere, externalState?.dismissed, externalState?.camelMarketCount, externalState?.henOrRoosterInMarket)
      resolvedTotals.set(key, computed.total)
      lines.push({ pos, cardId, name: card.name, base: computed.base, bonuses: computed.bonusLines, total: computed.total })
    }
  }

  // Pass 2: resolve Cow-shaped cards by MONOTONE VALUE RELAXATION, not a
  // "wait until every neighbor is fully resolved" pass — the latter
  // deadlocks on a legitimate case: two Cows adjacent to EACH OTHER that
  // are each ALSO adjacent to a non-Cow anchor (cowA neighbors {bee, cowB},
  // cowB neighbors {cowA, snail}) is not a cycle in the "no anchor" sense —
  // it has a well-defined answer (both converge to the higher of the two
  // anchors) — but neither cow's neighbor set is ever "fully resolved" if
  // resolution requires waiting for the other. Instead: each cow starts
  // unresolved, and every round takes the max over whichever neighbors
  // currently have SOME known value (from pass 1, or from a previous
  // round's own relaxation) — a value that can only ever increase, and is
  // bounded by the largest fame value anywhere in the grid, so this
  // converges in finitely many rounds. A Cow with zero adjacent face-up
  // cards is needsRuling immediately (no source covers that edge case — not
  // guessed). A Cow whose value never gets set because every neighbor is
  // itself an unset Cow, transitively, with no non-Cow anchor anywhere in
  // the chain — a genuine cycle — is needsRuling too, rather than forcing
  // an arbitrary fixed point.
  const cowSource = new Map<string, { cardId: CardId; pos: GridPos }>()
  const relaxable: typeof cowEntries = []
  for (const entry of cowEntries) {
    const neighbors = adjacentFaceUpEntries(entry.pos, grid)
    if (neighbors.length === 0) {
      entry.line.needsRuling = true
      entry.line.needsRulingReason = 'no adjacent face-up cards to copy fame from — this edge case is not covered by any source'
    } else if (neighbors.some((n) => dualBranchKeys.has(n.key))) {
      // A Cow adjacent to an unresolved Dog (dogElsewhere omitted) has no
      // single fame value either — its own max-of-adjacent copy would
      // otherwise silently ignore the Dog's higher true-branch value
      // (5) whenever some other neighbor is already resolved. Rather than
      // add a second dualBranch-of-a-dualBranch shape here, this is
      // flagged needsRuling — cheap and honest, per this file's existing
      // "needsRuling, not a guessed default" philosophy — instead of
      // silently reporting a total that's wrong in one branch. Pass
      // externalState.dogElsewhere explicitly to get a single resolved
      // Cow value.
      entry.line.needsRuling = true
      entry.line.needsRulingReason =
        "adjacent to a Dog whose fame is unresolved (externalState.dogElsewhere was not given) — this Cow's copied value depends on that same unresolved fact; pass --dog-elsewhere (or externalState.dogElsewhere) to resolve both together"
    } else {
      relaxable.push(entry)
    }
  }

  let changed = true
  let round = 0
  const maxRounds = relaxable.length + 2 // values only ever increase and are bounded, so this always terminates well before this cap; exceeding it is a real bug, not a legitimate large grid
  while (changed) {
    if (round++ > maxRounds) {
      throw new Error('score.ts: Cow fame relaxation did not converge within the expected number of rounds — this indicates a bug, not a legitimate grid state')
    }
    changed = false
    for (const entry of relaxable) {
      const neighbors = adjacentFaceUpEntries(entry.pos, grid)
      let best: { cardId: CardId; pos: GridPos; total: number } | null = null
      for (const n of neighbors) {
        const val = resolvedTotals.get(n.key)
        if (val === undefined) continue // neighbor not known yet (an unresolved Cow) — just skip it this round, don't block on it
        if (!best || val > best.total) best = { cardId: n.cardId, pos: n.pos, total: val }
      }
      if (best) {
        const prev = resolvedTotals.get(entry.key)
        if (prev === undefined || best.total > prev) {
          resolvedTotals.set(entry.key, best.total)
          cowSource.set(entry.key, { cardId: best.cardId, pos: best.pos })
          changed = true
        }
      }
    }
  }

  for (const entry of relaxable) {
    const val = resolvedTotals.get(entry.key)
    if (val === undefined) {
      entry.line.needsRuling = true
      entry.line.needsRulingReason =
        'forms a cycle of Cow-to-Cow adjacency with no non-Cow card anywhere in the chain to anchor a value — genuinely unresolvable, not a bug'
      continue
    }
    const src = cowSource.get(entry.key)!
    const srcCard = cardsById[src.cardId]
    entry.line.base = val
    entry.line.total = val
    entry.line.bonuses = [{ reason: `copied from ${srcCard.name} at ${posLabel(src.pos)}`, amount: 0 }]
    entry.line.copiedFrom = { cardId: src.cardId, name: srcCard.name, pos: src.pos }
  }

  const total = lines.reduce((sum, l) => sum + l.total, 0) // needsRuling / dualBranch lines carry total: 0 or the false-branch placeholder by construction

  // Grid-level mirror of any per-line dualBranch ambiguity: two grid totals
  // (never 2^n — every dualBranch line in one grid shares the same external
  // fact), one summing each line's false branch, one its true branch, and
  // any non-dualBranch line's plain `total` contributing to both.
  const hasDualBranchLine = lines.some((l) => l.dualBranch)
  const totalBranches = hasDualBranchLine
    ? [
        { label: DOG_ELSEWHERE_FALSE_LABEL, total: lines.reduce((sum, l) => sum + (l.dualBranch ? l.dualBranch[0].total : l.total), 0) },
        { label: DOG_ELSEWHERE_TRUE_LABEL, total: lines.reduce((sum, l) => sum + (l.dualBranch ? l.dualBranch[1].total : l.total), 0) },
      ]
    : undefined

  return { total, lines, totalBranches }
}

export function formatBreakdown(breakdown: FameBreakdown): string {
  const rows = breakdown.lines.map((line) => {
    if (line.needsRuling) {
      return `  ${posLabel(line.pos).padEnd(12)} ${line.name.padEnd(12)} NEEDS RULING (${line.needsRulingReason})`
    }
    if (line.dualBranch) {
      const branchText = line.dualBranch.map((b) => `${b.total} (${b.label})`).join(' | ')
      return `  ${posLabel(line.pos).padEnd(12)} ${line.name.padEnd(12)} ${branchText}`
    }
    const bonusText = line.bonuses.length
      ? ' + ' + line.bonuses.map((b) => `${b.amount} (${b.reason})`).join(' + ') + ` = ${line.total}`
      : ''
    return `  ${posLabel(line.pos).padEnd(12)} ${line.name.padEnd(12)} ${line.base}${bonusText}`
  })
  const totalText = breakdown.totalBranches
    ? breakdown.totalBranches.map((b) => `${b.total} (${b.label})`).join(' | ')
    : String(breakdown.total)
  return [...rows, `  ${'TOTAL'.padEnd(25)} ${totalText}`].join('\n')
}
